---
# Everything related to iOS
- name: Install mogenerator
  homebrew: name=mogenerator state=present

- name: Install iPhone Configuration Utility
  homebrew_cask: name=iphone-configuration-utility state=installed