---
# Everything related to ruby
- name: Install chruby
  homebrew: name=chruby state=present
- name: Install ruby-install
  homebrew: name=ruby-install state=present
- include: ruby-install.yml rubies={{ rubies }}
  vars:
    rubies:
      - {flavor: "ruby", version: "2.4"}
      - {flavor: "ruby", version: "2.5"}
      - {flavor: "ruby", version: "2.6"}
      - {flavor: "ruby", version: "2.7"}
